# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git' 
platform :ios, ‘9.0’
use_frameworks!

target ‘Checker’ do

pod 'AlamofireImage', '~> 2.0'
pod 'AlamofireObjectMapper', '~> 3.0'
pod 'Alamofire', '~> 3.4'
pod 'FoldingCell', '~> 0.8.1'

end


